apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # The ACME server URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: buerokratt@ria.ee
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging
    # Enable the HTTP-01 challenge provider
    solvers:
      - dns01:
          azureDNS:
            subscriptionID: b683ce64-51fa-4215-8064-e42408230343
            resourceGroupName: byk-pr49-rg
            hostedZoneName: byk-pr49-aks-ingress.westeurope.cloudapp.azure.com
            environment: AzurePublicCloud
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: buerokratt@ria.ee
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # Enable the HTTP-01 challenge provider
    solvers:
      - dns01:
          azureDNS:
            subscriptionID: b683ce64-51fa-4215-8064-e42408230343
            resourceGroupName: byk-pr49-rg
            hostedZoneName: byk-pr49-aks-ingress.westeurope.cloudapp.azure.com
            environment: AzurePublicCloud
