{{- $secrets := .Values.secrets | default dict -}}
{{- $mockClassifier := $secrets.mockClassifier | default dict -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mock-classifier.fullname" . }}-appsettings-secrets
  labels:
    {{- include "mock-classifier.labels" . | nindent 4 }}
type: Opaque
data:
  centOpsApiKey: {{ default "" $mockClassifier.centOpsApiKey | b64enc | quote }}