apiVersion: v1
kind: Service
metadata:
  name: {{ include "centops.fullname" . }}-service
  labels:
    {{- include "centops.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "centops.selectorLabels" . | nindent 4 }}
