apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dmr.fullname" . }}-appsettings-secrets
  labels:
    {{- include "dmr.labels" . | nindent 4 }}
type: Opaque
data:
  CosmosDbKey: {{ .Values.cosmosDbKey | b64enc | quote }}