{{- $secrets := .Values.secrets | default dict -}}
{{- $dmr := $secrets.dmr | default dict -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dmr.fullname" . }}-appsettings-secrets
  labels:
    {{- include "dmr.labels" . | nindent 4 }}
type: Opaque
data:
#Add secrets here