name: Infrastructure_cd
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths: ['.github/workflows/cd-infrastructure-*','.github/workflows/reusable-terraform-deployment','infrastructure/**']

jobs:
  Pr_deployment:
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    uses: ./.github/workflows/reusable-terraform-deployment.yml
    with:
      gh_environment: PR
      working_directory_path: infrastructure
      environment_name: pr
      environment_postfix: ${{ github.event.number }}
    secrets:
      azure_ad_client_id: ${{ secrets.AZURE_AD_CLIENT_ID }}
      azure_ad_client_secret: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      azure_ad_tenant_id: ${{ secrets.AZURE_AD_TENANT_ID }}
      azure_storage_account_key: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}