name: Infrastructure_cd
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths: ['.github/workflows/**','infrastructure/**']
  pull_request:
    branches:
      - main
    paths: ['.github/workflows/**','infrastructure/**']
    types: [opened, synchronize, closed]

env:
  IS_MAIN_BRANCH: github.event_name == 'push' && github.ref_name == 'main'

jobs:
  Pr_deployment:
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    uses: ./.github/workflows/reusable-terraform-deployment.yml
    with:
      gh_environment: PR
      working_directory_path: infrastructure
      environment_name: pr
      environment_postfix: ${{ github.event.number }}
    secrets:
      azure_ad_client_id: ${{ secrets.AZURE_AD_CLIENT_ID }}
      azure_ad_client_secret: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      azure_ad_tenant_id: ${{ secrets.AZURE_AD_TENANT_ID }}
      azure_storage_account_key: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
  Dev_deployment:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/reusable-terraform-deployment.yml
    with:
      gh_environment: Development
      working_directory_path: infrastructure
      environment_name: dev
    secrets:
      azure_ad_client_id: ${{ secrets.AZURE_AD_CLIENT_ID }}
      azure_ad_client_secret: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      azure_ad_tenant_id: ${{ secrets.AZURE_AD_TENANT_ID }}
      azure_storage_account_key: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
  Prod_deployment:
    needs: Dev_deployment
    uses: ./.github/workflows/reusable-terraform-deployment.yml
    with:
      gh_environment: Production
      working_directory_path: infrastructure
      environment_name: prod
    secrets:
      azure_ad_client_id: ${{ secrets.AZURE_AD_CLIENT_ID }}
      azure_ad_client_secret: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      azure_ad_tenant_id: ${{ secrets.AZURE_AD_TENANT_ID }}
      azure_storage_account_key: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
