name: Infrastructure_cd
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths: ['.github/workflows/**','infrastructure/**']
  pull_request:
    branches:
      - main
    paths: ['.github/workflows/**','infrastructure/**']

env:
  IS_MAIN_BRANCH: github.event_name == 'push' && github.ref_name == 'main'

jobs:
  Pr_deployment:
    if: github.event_name == 'pull_request'
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/reusable-terraform-deployment.yml
    with:
      gh_environment: PR
      working_directory_path: infrastructure
      tf_vars_file_path: environments/pr.tfvars
      backend_config_file_path: environments/backend/pr.conf
      environment_name: pr
      environment_postfix: ${{ github.event.number }}
    secrets:
      azure_ad_client_id: ${{ secrets.AZURE_AD_CLIENT_ID }}
      azure_ad_client_secret: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      azure_ad_tenant_id: ${{ secrets.AZURE_AD_TENANT_ID }}
      #TODO: Move this to key vault later on, this is required for the terraform backend setup
      azure_storage_account_key: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
  
  Dev_deployment:
    if: ${{ env.IS_MAIN_BRANCH == true }}
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/reusable-terraform-deployment.yml
    with:
      gh_environment: Development
      working_directory_path: infrastructure
      tf_vars_file_path: environments/dev.tfvars
      backend_config_file_path: environments/backend/dev.conf
      environment_name: dev
    secrets:
      azure_ad_client_id: ${{ secrets.AZURE_AD_CLIENT_ID }}
      azure_ad_client_secret: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      azure_ad_tenant_id: ${{ secrets.AZURE_AD_TENANT_ID }}
      #TODO: Move this to key vault later on, this is required for the terraform backend setup
      azure_storage_account_key: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}