name: Infrastructure_cd
on:
  push:
    branches:
    - main
    - feature/12-migrate-terraform-code
    - feature/aks-kubeconfig-secret
    paths: ['.github/workflows/**','infrastructure/**']
    
jobs:
  Dev_deployment:
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/reusable-terraform-deployment.yml
    with:
      environment: Development
      working_directory_path: infrastructure
      tf_vars_file_path: environments/dev.tfvars
      backend_config_file_path: environments/backend/dev.conf
    secrets:
      azure_ad_client_id: ${{ secrets.AZURE_AD_CLIENT_ID }}
      azure_ad_client_secret: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      azure_ad_tenant_id: ${{ secrets.AZURE_AD_TENANT_ID }}
      #TODO: Move this to key vault later on, this is required for the terraform backend setup
      azure_storage_account_key: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}