name: Infrastructure cd
on:
  push:
    branches:
    - yahya/features/mock-classifier-helm-chart
  
jobs:
  Kubernetes_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Helm
      uses: azure/setup-helm@v1

    - name: Lint Helm chart
      run: |
        helm lint ./helm-charts/mock-classifier
    
    #ToDo: sign chart
    - name: Package helm chart
      run: |
        mkdir -p temp/packages
        helm package ./helm-charts/mock-classifier --destination ./temp/packages
    
    - name: Upload package artifacts
      uses: actions/upload-artifact@v3.0.0
      with: 
        name: helm-packages
        path: ./temp/packages