#
# Setup workflow
# This workflow provisions the pre-requisite infrastructure resources for the DMR project.
#
# Note: This is a pipeline that needs to run once only.
#

name: Setup

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Azure CLI Login
        run: az login --service-principal -u ${{ secrets.AZURE_AD_CLIENT_ID }} -p ${{ secrets.AZURE_AD_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_AD_TENANT_ID }}

      - name: Azure CLI Action
        run: |
          chmod +x scripts/setup-project-prereqs.sh
          scripts/setup-project-prereqs.sh